### ISSUE TITLE
Contribution guidelines and or feature roadmap?

### ISSUE THREAD

**Issue by iantbutler01** [anshuman23/tensorflex#27]
Hi @anshuman23 , I was going to build out tensorflow bindings for elixir myself and was going to reachout to @versilov as well and I'd been periodically searching to see if someone had beat me to it and imagine my happiness as I finally stumbled on to this and let me say that I am ecstatic someone did beat me to it and I'd love to help contribute some development time to this project, I think its great for so many reasons and I think this could be amazing for the elixir community.

**Comment by anshuman23** [comment]
Thanks a lot for reaching out @GrandathePanda! :)

So I am currently writing tests for Tensorflex and in a couple of days will be releasing the Hex package following that. As soon as that is done I will put out contribution guidelines as well as possible features that can be added.

I will ping you here once that is done, and we can talk about future development work! In the meantime, it would be helpful if you check out the repository and play around with the examples, etc. and open up any issues that you may encounter. That would definitely help strengthen the library :)

Thanks again! :D

**Comment by iantbutler01** [comment]
Sounds good to me I will poke around when I get home from work today, and no problem.

**Comment by anshuman23** [comment]
Hello @GrandathePanda!

Tensorflex has now been released as a Hex package and the contribution guidelines are now added [here](https://github.com/anshuman23/tensorflex/blob/master/CONTRIBUTING.md) via PR #38. 

So I am closing this issue for now, but please open a new one if you would like to discuss an idea you have or anything related to development. Tensorflex can surely use more hands on deck! :)
