### ISSUE TITLE
Errors when adding Tensorflex to my application

### ISSUE THREAD

**Issue by murphycrosby** [anshuman23/tensorflex#43]
I'm gettting this error when adding {:tensorflex, github: "anshuman23/tensorflex"} to my mix.exs

Started ElixirLS debugger
Elixir version: "1.6.6 (compiled with OTP 20)"
Erlang version: "21"
(Debugger) Initialization failed because an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :on_load_failure}
        int.erl:531: anonymous fn/3 in :int.load/2
        int.erl:527: :int.load/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (debugger) lib/debugger/server.ex:473: ElixirLS.Debugger.Server.initialize/1
10:52:33.202 [error] Process #PID<0.108.0> raised an exception
** (MatchError) no match of right hand side value: {:error, :on_load_failure}
    int.erl:531: anonymous fn/3 in :int.load/2
    int.erl:527: :int.load/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2

Getting this error when adding {:tensorflex, "~> 0.1.2"} to my mix.exs

Started ElixirLS debugger
Elixir version: "1.6.6 (compiled with OTP 20)"
Erlang version: "21"
10:54:50.387 [warn]  The on_load function for module Elixir.Tensorflex.NIFs returned:
{:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/mhcrosb1/_git/Shipex/_build/dev/lib/tensorflex/priv/Tensorflex.so, 2): no suitable image found.  Did find:\n\t/Users/mhcrosb1/_git/Shipex/_build/dev/lib/tensorflex/priv/Tensorflex.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00\n\t/Users/mhcrosb1/_git/Shipex/_build/dev/lib/tensorflex/priv/Tensorflex.so: stat() failed with errno=35\''}}
(Debugger) Task failed because an exception was raised:
    ** (Mix.Error) Could not start application shipex_web: exited in: ShipexWeb.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :nxdomain}
            (statix) Elixir.Statix.Conn.erl:13: Statix.Conn.new/2
            (statix) Elixir.Statix.erl:324: Statix.new_conn/1

**Comment by synalysis** [comment]
Apparently the Tensorflex.so is built for Linux, not macOS.

After rebuilding for macOS it crashes when trying to call TF_SessionRun() in run_session(). 

The code is lacking some error handling so it crashes for example when you pass in tensors which don't exist in the graph. In my eyes this lib needs some work to make it production ready.

**Comment by murphycrosby** [comment]
How are you rebuilding for MacOS?

**Comment by synalysis** [comment]
> How are you rebuilding for MacOS?

I deleted the Tensorflex.so from `deps/tensorflex/priv`, then called `mix deps.compile`.

If you want to debug the lib with Xcode you should change the first line of Makefile to `CFLAGS = -g -O0 -Wall`(no optimization) in order to see all variables.

Setting up the debugger is a bit tricky: the easiest is to get the command line first with `ps ax | grep elixir` after running `iex -S mix`. In `iex`, run `System.get_env()` to get all env vars for the debugger.

**Comment by murphycrosby** [comment]
Thanks!  Was able to get it running in my app.  Was receiving the above errors in VSCode when trying to debug.  Seems to be fine in terminal.  The example worked, but I'm getting a seg fault as well when trying to run my custom model.

The keras model looks like this (input_shape=(26,)):
```
Layer (type)                 Output Shape              Param #   
=================================================================
dense_1 (Dense)              (None, 512)               13824     
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_3 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 513       
=================================================================
Total params: 539,649
Trainable params: 539,649
Non-trainable params: 0
```

I could have my tensors incorrect or my input_opname or output_opname incorrect.

```
{:ok, graph} = Tensorflex.read_graph("shipping_pred.pb")
in_dims = Tensorflex.create_matrix(1,26,[[2,2,2,10,100,1.50,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])
{:ok, input_tensor} = Tensorflex.float32_tensor_alloc(in_dims)
out_dims = Tensorflex.create_matrix(1,2,[[1]])
{:ok, output_tensor} = Tensorflex.float32_tensor_alloc(out_dims)
results = Tensorflex.run_session(graph, input_tensor, output_tensor, "dense_1", "dense_4")
```

**Comment by synalysis** [comment]
You could test my Tensorflex.c with some additional checks and changes - https://www.dropbox.com/s/tbtysl5m7z4znk5/Tensorflex.c?dl=0 - unfortunately I currently don't have the time to do further improvements in a fork.

**Comment by murphycrosby** [comment]
Finally got it resolved.  Feel free to close.

Thank you @synalysis, you led me in the right direction!  In the Tensorflex.c source, I had to add a TF_Message after TF_SessionRun to figure out why it was Segmentation faulting.

```
  TF_SessionRun(session, NULL, &input_op_o, &(*input_tensor), 1, 
    &output_op_o, &(*output_tensor), 1, 
    NULL, 0, NULL, status);
  
  if(TF_GetCode(status) != TF_OK) {
    fprintf(stderr, "TF_SessionRun Error - %s\n", TF_Message(status));
    return 0;
  }
```

The error said 

```
In[0] is not a matrix. Instead it has shape 
[2,2,2,10,100,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]

[[{{node dense_1_1/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_dense_1_input_0_0, dense_1_1/kernel)]]
```

The trick was in the input tensor.  Seems obvious now, but there didn't seem to be an example of passing an array, only loading an image.  But to pass an array there needs a val matrix as well as a dimension matrix.

```
    {:ok, graph} = Tensorflex.read_graph("shipping_pred.pb")
    in_vals = Tensorflex.create_matrix(1,26,[[2,2,2,10,100,1.50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]])
    in_dims = Tensorflex.create_matrix(1,2,[[1,26]])
    {:ok, input_tensor} = Tensorflex.float32_tensor(in_vals, in_dims)

    out_dims = Tensorflex.create_matrix(1,1,[[1]])
    {:ok, output_tensor} = Tensorflex.float32_tensor_alloc(out_dims)

    results = Tensorflex.run_session(graph, input_tensor, output_tensor, "dense_1_input", "dense_4_1/BiasAdd")
    res = List.flatten(results)
```

This now gives the expected results.

**Comment by anshuman23** [comment]
Thank you @synalysis for helping out! Glad the issue got resolved.
